version: '3.8'

services:
  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11435:11434"

  backend:
    build:
      context: ./backend
      dockerfile: Backend.cpu.dockerfile
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    depends_on:
      - ollama

  frontend:
    build:
      context: ./frontend/rag-ui
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/rag-ui:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  index_data:
  ollama:
